<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_LREAL_RoundToPlace" Id="{637cc13f-6279-4343-aeed-da6cb2a35a31}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LREAL_RoundToPlace : LREAL
VAR_INPUT
	fIn		: LREAL;
	nPlaces	: DINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LREAL_RoundToPlace := DINT_TO_LREAL(LREAL_TO_DINT(fIn * (nPlaces * 10)))/(nPlaces * 10);]]></ST>
    </Implementation>
    <LineIds Name="F_LREAL_RoundToPlace">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>