<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_RaiseAlarmWithStringParameters" Id="{0fae160d-14c3-4278-8cd1-635da75444f7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_RaiseAlarmWithStringParameters : BOOL
VAR_IN_OUT
	fbAlarm			: FB_TcAlarm;	//Alarm to be raised
END_VAR
VAR_INPUT
	sString_1	: STRING;
	sString_2	: STRING;
	sString_3	: STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAlarm.ipArguments.Clear();

fbAlarm.ipArguments.AddString(sString_1);
fbAlarm.ipArguments.AddString(sString_2);
fbAlarm.ipArguments.AddString(sString_3);

fbAlarm.Raise(0);]]></ST>
    </Implementation>
    <LineIds Name="F_RaiseAlarmWithStringParameters">
      <LineId Id="22" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="48" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="56" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>