<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_RaiseAlarmAndSetFlags" Id="{18d943ce-984b-4d83-a2cd-d13434a0acee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_RaiseAlarmAndSetFlags : BOOL
VAR_IN_OUT
	fbAlarm			: FB_TcAlarm;	//Alarm to be raised
	bErrorFlag		: BOOL;			//Error flag to set (VAR_IN_OUT, put the variable you want the function to SET here)
	nErrorID		: UDINT;			//Error ID to set (VAR_IN_OUT, put the variable you want the function to SET here) - Will be set using the ID of the given fbAlarm
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAlarm.ipArguments.Clear();

bErrorFlag	:= TRUE;
nErrorID := fbAlarm.nEventId;

fbAlarm.Raise(0);]]></ST>
    </Implementation>
    <LineIds Name="F_RaiseAlarmAndSetFlags">
      <LineId Id="22" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="95" Count="0" />
      <LineId Id="94" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>