<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Axis_HomeToMotorToque" Id="{9379d647-c9c4-4902-85f9-9d975d66d894}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Axis_HomeToMotorToque EXTENDS FB_Axis_HomeToHardStop
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="01_SUPER_Overrides" Id="{4daa08ef-b23d-49f5-8ecb-9bf0e97db98c}" />
    <Method Name="HardwareUpdate" Id="{96956867-482c-426e-a993-144b55dd7964}" FolderPath="01_SUPER_Overrides\">
      <Declaration><![CDATA[METHOD HardwareUpdate : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//nTorqueFeedback := SelectedAxis.NcToPlc.ActTorque / ;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Axis_HomeToMotorToque">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Axis_HomeToMotorToque.HardwareUpdate">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>